---
sudo: required

env:
  - distribution: alpine
    version: "3.10"

services:
  - docker

before_install:
  - >
    echo Get docker image ${distribution}:${version}.
    && sudo docker pull ${distribution}:${version}
  - >
    echo Build docker image ${distribution}:${version} for use with Ansible.
    && sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis

script:
  - container_id=$(mktemp)
  - >
    echo Create docker container from image ${distribution}-${version}:ansible.
    && sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-common:ro ${distribution}-${version}:ansible > "${container_id}"
  - >
    echo Get system facts for container ${distribution}-${version}:ansible.
    && sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible all -m setup

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
