---
dist: focal
addons:
  apt:
    packages:
      - python3-pip
      - python3-testresources
      - libssl-dev

language: minimal

services:
  - docker

env:
  global:
    - ROLE_NAME: ansible_bender
    - MOLECULE_DISTRO: coglinev3/ansible
    - PATH: /home/travis/.local/bin:${PATH}
  matrix:
    - MOLECULE_DISTRO_VERSION: centos-7
    - MOLECULE_DISTRO_VERSION: centos-8
    - MOLECULE_DISTRO_VERSION: debian-10
      MOLECULE_DISTRO_CMD: /bin/systemd
    - MOLECULE_DISTRO_VERSION: fedora-31
    - MOLECULE_DISTRO_VERSION: fedora-32
    - MOLECULE_DISTRO_VERSION: ubuntu-18.04
      MOLECULE_DISTRO_CMD: /bin/systemd
    - MOLECULE_DISTRO_VERSION: ubuntu-20.04
      MOLECULE_DISTRO_CMD: /bin/systemd

install:
  # Upgrade setuptools
  - python3 -m pip install --upgrade --user setuptools
  # Install Ansible Molecule with docker driver and lint tools
  - python3 -m pip install --upgrade --user "molecule[ansible,docker,lint]"

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv $(basename $TRAVIS_REPO_SLUG) $(dirname $TRAVIS_REPO_SLUG).${ROLE_NAME}
  - cd $(dirname $TRAVIS_REPO_SLUG).${ROLE_NAME}
  # Show Ansible and Molecule versions
  - ansible --version
  - molecule --version

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
