---
# file: roles/ansible_bender/tasks/main.yml

- name: Gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
  tags: vars


- name: Install extra repository.
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "repo-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "repo-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "repo-{{ ansible_distribution }}.yml"
        - "repo-{{ ansible_os_family }}.yml"
      skip: true

- name: "Include OS specific setup."
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Setup tasks.
  ansible.builtin.include_tasks: setup.yml

# Configuration tasks.
- name: Configure Ansible.
  ansible.builtin.include_tasks: configure-ansible.yml
- name: Configure Podman.
  ansible.builtin.include_tasks: configure-podman.yml
