---
# file: roles/ansible_bender/tasks/repo-Debian.yml

- name: Install GNU privacy guard
  become: "true"
  apt:
    name: gnupg2
    state: present
    update_cache: yes

- name: Install repository for buildah and podman
  become: "true"
  template:
    force: "no"
    src: kubic-apt-repo.j2
    dest: /etc/apt/sources.list.d/kubic-project.list
    owner: root
    group: root
    mode: 0644

- name: Add Apt key
  become: "true"
  apt_key:
    url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ ab_repo_prefix }}{{ ansible_distribution }}_{{ ansible_distribution_version }}/Release.key"
    state: present

- name: Update Apt cache
  become: "true"
  apt:
    update_cache: yes
