---
# file: roles/ansible_bender/tasks/repo-Debian-10.yml

- name: Install GNU privacy guard
  become: "true"
  apt:
    name: gnupg2
    state: present
    update_cache: yes

- name: "Debian: Set release for apt repository"
  set_fact:
    ab_distribution: "{{ ansible_distribution }}"
    ab_distribution_version: "{{ ansible_distribution_version }}"
  when: ansible_distribution != "Linux Mint"

- name: "Linux Mint: Set release and prefix for apt repository"
  set_fact:
    ab_distribution: Ubuntu
    ab_distribution_version: "{{ linux_mint_releases[ansible_distribution_release]['ubuntu_distribution_version'] }}"
    ab_repo_prefix: "x"
  when: ansible_distribution == "Linux Mint"

# - name: Install backports repository
#   become: "true"
#   template:
#     force: "no"
#     src: backports-repo.j2
#     dest: /etc/apt/sources.list.d/backports.list
#     owner: root
#     group: root
#     mode: 0644

- name: Add line for backports repository to sources.list
  become: "true"
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '^deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main'
    line: 'deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main'
    create: "yes"
    mode: 0644
    owner: root
    group: root

- name: Install repository for buildah and podman
  become: "true"
  template:
    force: "no"
    src: alvistack-apt-repo.j2
    dest: /etc/apt/sources.list.d/alvistack-project.list
    owner: root
    group: root
    mode: 0644

- name: Add Apt key
  become: "true"
  apt_key:
    url: "http://downloadcontent.opensuse.org/repositories/home:/alvistack/{{ ab_distribution }}_{{ ab_distribution_version }}/Release.key"
    state: present

- name: Update Apt cache
  become: "true"
  apt:
    update_cache: yes

- name: Update the repository cache and install libseccomp2 using backports release
  become: "true"
  ansible.builtin.apt:
    name: libseccomp2
    state: latest
    default_release: "{{ ansible_distribution_release }}-backports"
