---
# file: roles/ansible-bender/tasks/repo-Ubuntu.yml

- name: Install repository for buildah and podman
  become: "true"
  apt_repository:
    repo: ppa:projectatomic/ppa
    codename: "{{ ansible_distribution_release }}"
    update_cache: "yes"
  register: repo_result
  tags:
    - install
