---
# file: roles/ansible-bender/tasks/setup.yml

- name: "Install dependencies for ansible-bender."
  become: "true"
  ansible.builtin.package:
    name: "{{ ab_dependencies }}"
    state: "{{ ab_dependencies_package_state | default('present') }}"
  register: ab_dependencies_result
  when: not ansible_check_mode
  tags:
    - install

# - name: "Upgrade pip to the latest version "
#   become: "true"
#   ansible.builtin.pip:
#     name: pip
#     state: forcereinstall
#     executable: pip3

- name: "Install python dependencies"
  become: "true"
  ansible.builtin.pip:
    name: "{{ ab_python_dependencies }}"
    state: "{{ ab_python_package_state }}"
    umask: "0022"
    executable: pip3
  when: not ansible_check_mode
  environment:
    TMPDIR: /var/tmp
  tags:
    - install

- name: "Install ansible-bender"
  become: "true"
  ansible.builtin.pip:
    name: ansible-bender
    version: "{{ ab_version | default(omit) }}"
    umask: "0022"
    executable: pip3
  tags:
    - install
