---
# file: roles/ansible-bender/handlers/main.yml

- name: Sysctl_ping
  become: "true"
  ansible.builtin.command: sysctl -p /etc/sysctl.d/60-ping_group_range.conf

- name: Sysctl_max_user_namespace
  become: "true"
  ansible.builtin.command: sysctl -p /etc/sysctl.d/60-user_namespaces.conf

- name: Sysctl_user_namespace
  become: "true"
  ansible.builtin.service:
    name: procps
    state: restarted
