---
- name: Converge
  hosts: all
  tasks:
    - name: "Include coglinev3.ansible_bender"
      include_role:
        name: "coglinev3.ansible_bender"

    - name: "Get podman informations"
      command: >
        podman
        --storage-driver=vfs
        info
      register: podman_info
    - debug:
        var: podman_info
    - name: "Get ansible-bender version"
      command: ansible-bender --version
      register: bender_version
    - debug:
        var: bender_version
