---
# file: roles/ansible_bender/molecule/default//converge.yml

- name: Converge
  hosts: all
  vars:
    ab_users:
      - ansible
  tasks:
    - name: "Include coglinev3.ansible_bender"
      include_role:
        name: "coglinev3.ansible_bender"
